### ISSUE TITLE
生成的markdown没有跳转链接

### ISSUE THREAD

**Issue by mingyun** [phodal/md#1]
今天刚使用mdpub来写文章，但是`[mdpub](https://github.com/phodal/mdpub)` 这种在微信种链接不可点击，希望更新修复下，感谢。

**Comment by phodal** [comment]
@mingyun 你可以确定你的公众号可以放外链么？只有认证过的公众号才能放外链

**Comment by mingyun** [comment]
@phodal 这样啊，我的公众号的确木有认证。。。
