### ISSUE TITLE
可以做成桌面版本的，浏览器里面下拉很吃力。

### ISSUE THREAD

**Issue by strongant** [phodal/md#3]

**Comment by phodal** [comment]
下拉很吃力是指？

**Comment by strongant** [comment]
就是左边编辑框往下拉长几下就拉不动了！

**Comment by phodal** [comment]
@strongant 我一般都是在自己的电脑上写，然后直接粘贴到上面的，再复制出内容

**Comment by strongant** [comment]
![mdpub](https://cloud.githubusercontent.com/assets/7685936/21747821/4033d13e-d5af-11e6-8fc6-8dd674d95a27.png)

**Comment by justjavac** [comment]
@strongant 这个是用来排版的，不是用来编辑的。所以，电脑上编辑完，然后复制过来
