### ISSUE TITLE
如何更改颜色配置？

### ISSUE THREAD

**Issue by liutaoibm** [phodal/md#5]
首先工具很好用，非常感谢。一个问题是在文本本拷贝到微信的输入框里后，还可以更改一些文本的颜色么？另外是否可以支持多种不同配色方案？

**Comment by phodal** [comment]
拷贝到微信上可以修改文本的颜色。

支持不同的配色方案是指字体的？还是代码？

**Comment by liutaoibm** [comment]
代码的配色方案，修改颜色也是指代码里的，我用别的编辑器更改html的方法已经能够修改代码里的颜色，但是发现另外一个问题，我新开一个吧
