### ISSUE TITLE
代码在android显示不换行

### ISSUE THREAD

**Issue by liutaoibm** [phodal/md#6]
一个例子：https://mp.weixin.qq.com/s?__biz=MzU5OTAxNjE5Mw==&mid=2247483658&idx=1&sn=54d26e5056263d9da06cdc01491ab106&chksm=feba1764c9cd9e72b4db52d64beddbacd893c8c5c3752b16499a17136ba9e6d95a2524e2ce5b&scene=0&key=12cbaa18475f5c7e297ee1c91b7f64eb3eed8687fd8c7100ad8472bd19d3e35fd0f0d425eedfe7eedbdfb8a674d82fb0af18542e2c785d9e70dfdf298a36d6f7395e6c09a884e30724cfed734fd3da04&ascene=0&uin=MTA5MTU2MzQ4MQ%3D%3D&devicetype=iMac+MacBookPro11%2C5+OSX+OSX+10.12.3+build(16D32)&version=12010310&nettype=WIFI&fontScale=100&pass_ticket=uoGOACebTMrY2%2BnlTsEf3EXzHPbhcVscNsfRMsYSiwfAPD58hW032NJe%2F14%2Blyd9

在ios显示换行但有点乱，如果改成用一个可以拖动的box显示会不会更好？
在android则不换行，看不全

**Comment by phodal** [comment]
@liutaoibm 最初设计的时候就是设计为不换行的。

在微信公众号上的代码阅读体验比较差。。并且，不建议在碎片时间阅读代码

**Comment by liutaoibm** [comment]
我这个不是研究什么代码啦，只是一个记录而已
